name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
    - name: Check Rust file changes
      id: rust_changes
      run: echo "::set-output name=changes::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.rs$')"
    - name: Install dependencies
      run: |
        if [[ -n "${{ steps.rust_changes.outputs.changes }}" ]]; then
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev build-essential libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
        fi
    - name: Build
      run: |
        if [[ -n "${{ steps.rust_changes.outputs.changes }}" ]]; then
          mkdir exbot-app/dist
          cargo build
        fi
    - name: Run tests
      run: |
        if [[ -n "${{ steps.rust_changes.outputs.changes }}" ]]; then
          cargo test --verbose
        fi
